# Generated by Django 5.1.5 on 2025-04-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=50),
        ),
    ]
